### ISSUE TITLE
Querying previous sometimes hangs if it goes beyond the oldest item

### ISSUE THREAD

**Issue by benFlightStats** [flightstats/hub#149] opened 2015-04-17 00:05 UTC
Lucas was having an issue with this:

http://hub-v2.svc.staging/channel/kratzen_lgw_last/2015/04/16/23/49/13/164/TrNHM6/previous/7
would hang
but 
http://hub-v2.svc.staging/channel/kratzen_lgw_last/2015/04/16/23/49/13/164/TrNHM6/previous/6
would return quickly

**Comment by moulliet** [comment] 2015-04-17 03:16
The issue here is the ttlDays of the channel, set to 604800000 (which may be from V1's ttlMillis, and probably makes more sense as 7 days).
If you use /previous in V2 which spans past the first item, the hub will search in S3 for the entire ttlDays, which will take a *long* time.  The quick fix is to use a reasonable ttlDays.
This may also be related to #144.

**Comment by moulliet** [comment] 2015-04-22 18:56
this is a duplicate of #144

**Closed by moulliet** 2015-04-22 18:56 UTC
